// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: youthumb/v1/youthumb.proto

package youthumbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ThumbnailChunk represents a chunk of thumbnail data. The content type is
// a MIME type of the data and is sent only once in the first message.
type ThumbnailChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// content_type is a MIME type of the data.
	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// data is a chunk of thumbnail data.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ThumbnailChunk) Reset() {
	*x = ThumbnailChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_youthumb_v1_youthumb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThumbnailChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailChunk) ProtoMessage() {}

func (x *ThumbnailChunk) ProtoReflect() protoreflect.Message {
	mi := &file_youthumb_v1_youthumb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailChunk.ProtoReflect.Descriptor instead.
func (*ThumbnailChunk) Descriptor() ([]byte, []int) {
	return file_youthumb_v1_youthumb_proto_rawDescGZIP(), []int{0}
}

func (x *ThumbnailChunk) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ThumbnailChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetThumbnailRequest represents a request to get a thumbnail of a video.
type GetThumbnailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// video_url is a URL of the video for which a thumbnail should be sent.
	VideoUrl string `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
}

func (x *GetThumbnailRequest) Reset() {
	*x = GetThumbnailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_youthumb_v1_youthumb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailRequest) ProtoMessage() {}

func (x *GetThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_youthumb_v1_youthumb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailRequest.ProtoReflect.Descriptor instead.
func (*GetThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_youthumb_v1_youthumb_proto_rawDescGZIP(), []int{1}
}

func (x *GetThumbnailRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

var File_youthumb_v1_youthumb_proto protoreflect.FileDescriptor

var file_youthumb_v1_youthumb_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x79, 0x6f, 0x75, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x79, 0x6f,
	0x75, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x79, 0x6f,
	0x75, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x2e, 0x76, 0x31, 0x22, 0x47, 0x0a, 0x0e, 0x54, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x32, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x55, 0x72, 0x6c, 0x32, 0x63, 0x0a, 0x10, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e,
	0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x2e, 0x79, 0x6f, 0x75,
	0x74, 0x68, 0x75, 0x6d, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x68, 0x75, 0x6d,
	0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x79,
	0x6f, 0x75, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62,
	0x6e, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x42, 0x4d, 0x5a, 0x4b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x72, 0x69, 0x6c, 0x6c,
	0x67, 0x61, 0x73, 0x68, 0x6b, 0x6f, 0x76, 0x2f, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x2d, 0x79, 0x6f, 0x75, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x79, 0x6f, 0x75, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x3b,
	0x79, 0x6f, 0x75, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_youthumb_v1_youthumb_proto_rawDescOnce sync.Once
	file_youthumb_v1_youthumb_proto_rawDescData = file_youthumb_v1_youthumb_proto_rawDesc
)

func file_youthumb_v1_youthumb_proto_rawDescGZIP() []byte {
	file_youthumb_v1_youthumb_proto_rawDescOnce.Do(func() {
		file_youthumb_v1_youthumb_proto_rawDescData = protoimpl.X.CompressGZIP(file_youthumb_v1_youthumb_proto_rawDescData)
	})
	return file_youthumb_v1_youthumb_proto_rawDescData
}

var file_youthumb_v1_youthumb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_youthumb_v1_youthumb_proto_goTypes = []any{
	(*ThumbnailChunk)(nil),      // 0: youthumb.v1.ThumbnailChunk
	(*GetThumbnailRequest)(nil), // 1: youthumb.v1.GetThumbnailRequest
}
var file_youthumb_v1_youthumb_proto_depIdxs = []int32{
	1, // 0: youthumb.v1.ThumbnailService.GetThumbnail:input_type -> youthumb.v1.GetThumbnailRequest
	0, // 1: youthumb.v1.ThumbnailService.GetThumbnail:output_type -> youthumb.v1.ThumbnailChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_youthumb_v1_youthumb_proto_init() }
func file_youthumb_v1_youthumb_proto_init() {
	if File_youthumb_v1_youthumb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_youthumb_v1_youthumb_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ThumbnailChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_youthumb_v1_youthumb_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetThumbnailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_youthumb_v1_youthumb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_youthumb_v1_youthumb_proto_goTypes,
		DependencyIndexes: file_youthumb_v1_youthumb_proto_depIdxs,
		MessageInfos:      file_youthumb_v1_youthumb_proto_msgTypes,
	}.Build()
	File_youthumb_v1_youthumb_proto = out.File
	file_youthumb_v1_youthumb_proto_rawDesc = nil
	file_youthumb_v1_youthumb_proto_goTypes = nil
	file_youthumb_v1_youthumb_proto_depIdxs = nil
}
